### PR TITLE
#256Create Bitget

### PR DESCRIPTION
**Pull request by Allenqel**
import hashlib

def sha256_hash(data):
    """Hashes the input data using SHA-256."""
    return hashlib.sha256(data.encode('utf-8')).hexdigest()

def build_merkle_root(leaf_hashes):
    """Builds the Merkle root from a list of leaf hashes."""
    if len(leaf_hashes) == 1:
        return leaf_hashes[0]  # Root reached

    # If odd number of leaves, duplicate the last one
    if len(leaf_hashes) % 2 != 0:
        leaf_hashes.append(leaf_hashes[-1])

    # Pairwise hash leaves
    parent_hashes = []
    for i in range(0, len(leaf_hashes), 2):
        combined_hash = sha256_hash(leaf_hashes[i] + leaf_hashes[i + 1])
        parent_hashes.append(combined_hash)

    return build_merkle_root(parent_hashes)

# Provided Merkle leaves (from the data)
merkle_leaves = [
    "8cf0243a2c76fe0b",  # Path 1
    "8306844dff98ba79",  # Path 2
    "94d0d60f7cdce5fe",  # Path 3
    "cb575fb1eb6462f9",  # Self
]

# Compute Merkle Root
calculated_merkle_root = build_merkle_root(merkle_leaves) print(f"Calculated Merkle Root: {calculated_merkle_root}")

### CODE REVIEW

**Comment by Allenqel** [comment]
#90

**Comment by Saingsophea** [comment]
# If odd number of leaves, duplicate the last one
if len(leaf_hashes) % 2 != 0:
    leaf_hashes.append(leaf_hashes[-1])

# Pairwise hash leaves
parent_hashes = []
for i in range(0, len(leaf_hashes), 2):
    combined_hash = sha256_hash(leaf_hashes[i] + leaf_hashes[i + 1])
    parent_hashes.append(combined_hash)

return build_merkle_root(parent_hashes)

**Review by Sandra-Amina-Boss — APPROVED** [review]

**Comment by Allenqel** [comment]
#256

**Comment by Saingsophea** [comment]
[@Saingsophea ](url)

**Review by Sandra-Amina-Boss — APPROVED** [review]

**Pull request closed without merging**
